//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EzMaxPlugin.rc
//
#define IDS_EZ_CLASS_NAME               101
#define IDS_EXPORT_CLASS_NAME           102
#define IDS_CATEGORY                    103
#define IDD_PANEL                       104
#define IDS_EXPORT_CATEGORY             105
#define IDD_EXPORT_PANEL                106
#define IDS_LIBDESCRIPTION              107
#define IDS_EXPORT_LIBDESCRIPTION       108
#define IDS_EXPORT_INTERNALNAME         109
#define IDS_STRING105                   110
#define IDS_EXPORT_LONGDESCRIPTION      111
#define IDS_EXPORT_SHORTDESCRIPTION     112
#define IDD_EZSHADER                    113
#define IDS_EXPORT_SHORTDESCRIPTION2    114
#define IDS_EXPORT_AUTHORNAME           115
#define IDS_SHADER_CLASS_NAME           116
#define IDS_SHADER_NAME                 117
#define IDS_SHADER_PARAMETERS_NAME      118
#define IDS_SHADER_BASIC                119
#define IDS_RB_SEGS                     120
#define IDS_RB_SMOOTH                   121
#define IDS_RB_PRIMITIVES               122
#define IDS_RB_SPHERE                   123
#define IDS_RB_RADIUS1                  124
#define IDS_RB_RADIUS2                  125
#define IDS_RB_SPHERE_CLASS             126
#define IDS_DS_PARAMCHG                 127
#define IDS_DS_LAYER                    128
#define IDS_DS_MATERIAL                 129
#define IDS_DS_NODE                     130
#define IDS_DS_PRIORITY                 131
#define IDS_DS_COLLISION                132
#define IDS_PICKNODE                    133
#define IDS_PICKNODE_PROMPT             134
#define IDS_RB_BOX                      135
#define IDS_VERTEXCOLORENABLE           136
#define IDS_SRC_VERTEX_MODE             137
#define IDS_LIGHTING_MODE               138
#define IDS_APPLY_MODE                  139
#define IDS_TEST_REF                    140
#define IDS_TEST_MODE                   141
#define IDS_ALPHATEST_ENABLE            142
#define IDS_ALPHA_NOSORTER              143
#define IDS_BUMP_MAGNITUDE              144
#define IDS_LUMA_SCALE                  145
#define IDS_LUMA_OFFSET                 146
#define IDS_RB_FIXDUPL                  147
#define IDS_RB_SELUNUSED                148
#define IDS_MAT_DIFFUSE                 149
#define IDS_MAT_SPECULAR                150
#define IDS_MAT_SELFILLUMCLR            151
#define IDS_MAT_SELFILLUM               152
#define IDS_MAT_GLOSSINESS              153
#define IDS_MAT_SPECLEVEL               154
#define IDS_MAT_SOFTENLEVEL             155
#define IDS_MAT_SHININESS               156
#define IDS_MAT_AMBIENT                 157
#define IDS_MAT_EMITTANCE               158
#define IDS_MAT_SELFILLUMON             159
#define IDS_MAT_SPECULARENABLE          160
#define IDS_MAT_ALPHA                   161
#define IDS_MAT_DITHER                  162
#define IDS_ALPHA_MODE                  163
#define IDS_ALPHA_SRC                   164
#define IDS_ALPHA_DEST                  165
#define IDS_CHAN_BASE                   166
#define IDS_CHAN_DARK                   167
#define IDS_CHAN_DETAIL                 168
#define IDS_CHAN_GLOSS                  169
#define IDS_CHAN_GLOW                   170
#define IDS_CHAN_BUMP                   171
#define IDS_CHAN_NORMAL                 172
#define IDS_CHAN_UNK2                   173
#define IDS_CHAN_DECAL1                 174
#define IDS_CHAN_DECAL2                 175
#define IDS_CHAN_DECAL3                 176
#define IDS_CHAN_ENVMASK                177
#define IDS_CHAN_ENV                    178
#define IDS_CHAN_OPACITY                179
#define IDS_CHAN_HEIGHT                 180
#define IDS_CHAN_REFLECTION             181
#define IDS_CHAN_EMPTY                  182
#define IDS_MAXCHAN_DIFFUSE             183
#define IDS_MAXCHAN_SELFILLUMMAP        184
#define IDS_MAXCHAN_NORMAL              185
#define IDS_MAXCHAN_GLOW                186
#define IDS_MAXCHAN_GLOSS               187
#define IDS_MAXCHAN_DETAIL              188
#define IDS_MAXCHAN_BUMP                189
#define IDS_MAXCHAN_EMPTY               190
#define IDC_CHECK1                      1001
#define IDC_CHECK2                      1002
#define IDC_CHECK3                      1003
#define IDC_CHECK4                      1004
#define IDC_CHECK5                      1005
#define IDC_CHK_STRIPS                  1006
#define IDC_CHECK7                      1007
#define IDC_CHK_VERTEXCOLORS            1007
#define IDC_CHECK8                      1008
#define IDC_CHECK9                      1009
#define IDC_CHECK10                     1010
#define IDC_CHECK11                     1011
#define IDC_EDIT1                       1012
#define IDC_EDIT2                       1013
#define IDC_COMBO1                      1014
#define IDC_CBO_ANIM_TYPE               1014
#define IDC_CHECK12                     1015
#define IDC_EDIT3                       1016
#define IDC_CLR_AMBIENT                 1018
#define IDC_ED_TEXPREFIX                1019
#define IDC_CLR_DIFFUSE                 1020
#define IDC_CHK_SPECENABLE              1021
#define IDC_CLR_EMITTANCE               1022
#define IDC_EDT_SHININESS               1023
#define IDC_SPN_SHININESS               1024
#define IDC_EDT_ALPHA                   1025
#define IDC_SPN_ALPHA                   1026
#define IDC_CHK_DITHER                  1027
#define IDC_CHK_VERTEXENABLE            1028
#define IDC_CBO_VERTEX_SRC              1029
#define IDC_CBO_VERTEX_LIGHT            1030
#define IDC_RDO_TRANS_AUTO              1031
#define IDC_RDO_TRANS_NONE              1032
#define IDC_RDO_TRANS_STD               1033
#define IDC_RDO_TRANS_ADV               1034
#define IDC_RDO_TRANS_ADD               1035
#define IDC_RDO_TRANS_MULT              1036
#define IDC_CHK_ALPHATESTENABLE         1037
#define IDC_CHK_NOSORTER                1038
#define IDC_EDT_TESTREF                 1039
#define IDC_SPN_TESTREF                 1040
#define IDC_CBO_TESTMODE                1041
#define IDC_CBO_TRANS_SRC               1042
#define IDC_CBO_TRANS_DEST              1043
#define IDC_CBO_APPLY_MODE              1044
#define IDC_CUSTOM_SHADER               1045
#define IDC_COLOR                       1048
#define IDC_MAPON_CLR                   1049
#define IDC_HIGHLIGHT                   1050
#define IDC_GL_EDIT                     1051
#define IDC_GL_SPIN                     1052
#define IDC_MAPON_GL                    1053
#define IDC_MT_EDIT                     1054
#define IDC_MT_SPIN                     1055
#define IDC_MAPON_MT                    1056
#define IDC_TR_EDIT                     1057
#define IDC_TR_SPIN                     1058
#define IDC_MAPON_TR                    1059
#define IDC_CLR_SPECULAR                10202
#define IDC_MAP_DIFFUSE                 10211

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        107
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1047
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
